In [2]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [5]:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

X_test = np.array([[ 2., -1.,  1.],
                   [ 3.,  3., -1.],
                   [ 1.,  1.,  1.]])

# fit and scale training data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

print("Scaled X_train:\n", X_train_scaled)
print("Feature-wise mean (training):", scaler.mean_)
print("Feature-wise std (training):", np.sqrt(scaler.var_))

Scaled X_train:
 [[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
Feature-wise mean (training): [1.         0.         0.33333333]
Feature-wise std (training): [0.81649658 0.81649658 1.24721913]


In [6]:
print("Mean after scaling:", X_train_scaled.mean(axis=0))
print("Std after scaling:", X_train_scaled.std(axis=0))

Mean after scaling: [0. 0. 0.]
Std after scaling: [1. 1. 1.]
